name: Build OpenWrt with proxy_connect

on:
  workflow_dispatch:

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout OpenWrt source
      run: |
        git clone --depth=1 https://github.com/openwrt/openwrt.git
        cd openwrt
        # 切你需要的版本或分支，例如：
        # git checkout openwrt-24.10

    - name: Clone ngx_http_proxy_connect_module
      run: |
        cd openwrt/package
        git clone https://github.com/chobits/ngx_http_proxy_connect_module.git

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc unzip python3 python3-distutils zlib1g-dev file wget

    - name: Prepare config
      run: |
        cd openwrt
        # 生成默认配置（你可以先准备一个.config文件放仓库用 checkout）
        make defconfig
        # 如果你有自定义配置，这里替换为：
        # cp ../your_config .config
        # make defconfig

    - name: Build OpenWrt firmware
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/
