name: Build OpenWrt Nginx with proxy_connect_module

on:
  workflow_dispatch:

env:
  CACHE_KEY: ${{ runner.os }}-openwrt-${{ hashFiles('**/feeds.conf.default') }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache OpenWrt
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          openwrt
          dl
        key: ${{ env.CACHE_KEY }}

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex gawk gcc-multilib \
            gettext git libncurses-dev libssl-dev python3-distutils rsync unzip \
            zlib1g-dev file wget python3 python3-pip python3-setuptools subversion

    - name: Setup OpenWrt
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        git clone --depth=1 https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        mkdir -p package
        cd package
        git clone https://github.com/chobits/ngx_http_proxy_connect_module.git
        cd ..

    - name: Configure Nginx
      run: |
        cd openwrt
        [ ! -d "package/ngx_http_proxy_connect_module" ] && \
          git clone https://github.com/chobits/ngx_http_proxy_connect_module.git package/ngx_http_proxy_connect_module
        
        echo "CONFIG_PACKAGE_nginx=y" >> .config
        echo "CONFIG_PACKAGE_nginx-ssl=y" >> .config
        echo "CONFIG_PACKAGE_nginx-mod-http-lua=y" >> .config
        echo "CONFIG_PACKAGE_nginx-mod-http-proxy-connect=y" >> .config
        make defconfig

    - name: Build packages
      run: |
        cd openwrt
        make -j$(nproc) package/nginx/compile V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nginx-ipk
        path: openwrt/bin/packages/*/base/nginx*proxy-connect*.ipk
